import type { Metadata } from 'next';
import { Inter } from 'next/font/google';


import '../styles/globals.css';

import { StoreProvider } from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Parking Automater',
  description: 'Generated by the Parkers',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>{children}</StoreProvider>

      </body>
    </html>
  );
}